extends Upgrade
class_name CCU02StardustBoost
## CCU02 : Improves stardust generated per second. See Ep 11, "More CC Upgrades"

## Maximum upgrades
var max_level : int = 5

## Initialization values
func _init() -> void:
	level = Game.ref.data.cc_upgrades.u_02_stardust_boost_level
	title = "Stardust Generator Efficiency"
	base_cost = 1
	cost = 1

## Returns the description of the upgrade
func description() -> String:
	var text : String = "Increases the amount of passive Stardust generated by the Universe per second."
	text += "\n[b]Effects :[/b] +1 Stardust per second"
	if level < max_level:
		text += "\n[b]Cost :[/b] %s Consciousness Core" %cost
	return text

## Returns whether the upgrade is available and affordable
func can_afford() -> bool:
	if level >= max_level:
		return false
	if Game.ref.data.consciousness_core >= cost:
		return true
	return false

## Consumes CCs, increments upgrade level
func level_up() -> void:
	if level >= max_level:
		return
	var error : Error = HandlerConsciousnessCore.ref.consume_consciousness_core(cost)
	if error:
		return
	level += 1
	Game.ref.data.cc_upgrades.u_02_stardust_boost_level = level
	leveled_up.emit()
	HandlerCCUpgrades.ref.upgrade_leveled_up.emit(self)
